import type { NextPage } from 'next'
import Head from 'next/head'

import { Box } from '@mui/material'

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>No Doubt!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        {'header'}
      </header>
      <main>
      {'InitialDisplay'}
      </main>
      <footer>
      {'fooder'}
      </footer>
    </Box>
  )
}

export default Home
